/**
 * Seleções participantes da Copa do Mundo 2026
 * Total: 32 seleções
 */
export const SELECOES_COPA_2026 = [
  "Argentina",
  "Austrália",
  "Bélgica",
  "Brasil",
  "Canadá",
  "Camarões",
  "Coreia do Sul",
  "Costa Rica",
  "Croácia",
  "Dinamarca",
  "Egito",
  "Espanha",
  "Estados Unidos",
  "Escócia",
  "França",
  "Gana",
  "Grécia",
  "Holanda",
  "Honduras",
  "Hungria",
  "Inglaterra",
  "Irã",
  "Irlanda",
  "Itália",
  "Japão",
  "Marrocos",
  "México",
  "Polônia",
  "Portugal",
  "Sérvia",
  "Suíça",
  "Tunísia",
  "Turquia",
  "Uruguai",
].sort();
